//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PracticeStudyCenterEntities : DbContext
    {
        private static PracticeStudyCenterEntities _context;

        public static PracticeStudyCenterEntities GetContext()
        {
            if (_context == null)
            {
                _context = new PracticeStudyCenterEntities();
            }
            return _context;
        }
        public PracticeStudyCenterEntities()
            : base("name=PracticeStudyCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        internal void Open()
        {
            throw new NotImplementedException();
        }

        public virtual DbSet<Assignments> Assignments { get; set; }
        public virtual DbSet<Certificates> Certificates { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfo { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<IndividualLessons> IndividualLessons { get; set; }
        public virtual DbSet<PaymentType> PaymentType { get; set; }
        public virtual DbSet<Solutions> Solutions { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentGroup> StudentGroup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeCourse> TypeCourse { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStatus> UserStatus { get; set; }
    }
}
