//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solutions
    {
        public int SolutionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public byte[] SolutionFile { get; set; }
        public string StudentComment { get; set; }
        public string TeacherComment { get; set; }
        public Nullable<bool> Grade { get; set; }
    
        public virtual Assignments Assignments { get; set; }
        public virtual Student Student { get; set; }
        public virtual Users Users { get; set; }
    }
}
