//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentGroup
    {
        public int StudentGroupID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> GroupID { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual Student Student { get; set; }
    }
}
